server:
  port: 8088
  
spring:
  application:
    name: dubbo-demo-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=utf8
    username: root
    password:
dubbo:
  scan:
    base-packages: io.kimmking.dubbo.demo.provider
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181

mybatis:
  type-aliases-package: org.dromara.hmily.demo.common.account.entity
  config-location: classpath:mybatis/mybatis-config.xmlhmily.yml